export const actionTypes = {
    FETCHING_START: "FETCHING_START",
    FETCHING_ERROR: "FETCHING_ERROR",
    FETCHING_SUCCESS: "FETCHING_SUCCESS",
    FETCHING_TOGGLE: "FETCHING_TOGGLE",
    ADD_TO_CART: "ADD_TO_CART"
}